import libs += libboost-beast%lib{boost_beast}
import libs += libboost-date-time%lib{boost_date_time}
import intf_libs += libboost-program-options%lib{boost_program_options}
import intf_libs += libbacktrace%lib{backtrace}
import intf_libs += libdatatree%lib{datatree}
import intf_libs += libcrails-logger%lib{crails-logger}
import intf_libs += libcrails-semantics%lib{crails-semantics}
import intf_libs += libcrails-readfile%lib{crails-readfile}
import intf_libs += libcrails-renderer%lib{crails-renderer}

lib{crails}: {hxx ixx txx cxx}{** -crails/version} hxx{crails/version} $impl_libs $intf_libs

hxx{crails/version}: in{crails/version} $src_root/manifest

hxx{export}@./: cxx.importable = false

# Build options.
#
cxx.poptions =+ "-I$out_root" "-I$src_root"

{hbmia obja}{*}: cxx.poptions += -DLIBCRAILS_STATIC_BUILD
{hbmis objs}{*}: cxx.poptions += -DLIBCRAILS_SHARED_BUILD

# Export options.
#
lib{crails}:
{
  cxx.export.poptions = "-I$out_root/libcrails/" "-I$src_root/libcrails/"
  cxx.export.libs = $intf_libs
}

liba{crails}: cxx.export.poptions += -DLIBCRAILS_STATIC
libs{crails}: cxx.export.poptions += -DLIBCRAILS_SHARED

# For pre-releases use the complete version to make sure they cannot be used
# in place of another pre-release or the final version. See the version module
# for details on the version.* variable values.
#
if $version.pre_release
  lib{crails}: bin.lib.version = "-$version.project_id"
else
  lib{crails}: bin.lib.version = "-$version.major.$version.minor"

# Install into the crails/ subdirectory of, say, /usr/include/
# recreating subdirectories.
#
{hxx ixx txx}{*}:
{
  install         = include/
  install.subdirs = true
}
